/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugalsan.dsk.serialyh;

import com.tugalsan.api.serialcom.kincony.server.KC868_A32_R1_2.TS_SerialComKinConyKC868_A32_R1_2;
import com.tugalsan.api.time.client.TGS_Time;

/**
 *
 * @author tugal
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabTest = new javax.swing.JTabbedPane();
        pnlMonitor = new javax.swing.JTabbedPane();
        pnlTest = new javax.swing.JPanel();
        scrollReply = new javax.swing.JScrollPane();
        taReply = new javax.swing.JTextArea();
        lblReply = new javax.swing.JLabel();
        lblCmd = new javax.swing.JLabel();
        btnCmdChipName = new javax.swing.JButton();
        btnCmdDigitalInGetAll = new javax.swing.JButton();
        btnCmdDigitalOutGetAll = new javax.swing.JButton();
        btnCmdMemIntGetAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabTest.addTab("İzle", pnlMonitor);

        taReply.setColumns(20);
        taReply.setRows(5);
        scrollReply.setViewportView(taReply);

        lblReply.setText("Reply:");

        lblCmd.setText("Komutlar:");

        btnCmdChipName.setText("chipName");
        btnCmdChipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmdChipNameActionPerformed(evt);
            }
        });

        btnCmdDigitalInGetAll.setText("digitalIn.GetAll");
        btnCmdDigitalInGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmdDigitalInGetAllActionPerformed(evt);
            }
        });

        btnCmdDigitalOutGetAll.setText("digitalOut.GetAll");
        btnCmdDigitalOutGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmdDigitalOutGetAllActionPerformed(evt);
            }
        });

        btnCmdMemIntGetAll.setText("memInt.GetAll");
        btnCmdMemIntGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmdMemIntGetAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTestLayout = new javax.swing.GroupLayout(pnlTest);
        pnlTest.setLayout(pnlTestLayout);
        pnlTestLayout.setHorizontalGroup(
            pnlTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollReply, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(lblReply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTestLayout.createSequentialGroup()
                .addGroup(pnlTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTestLayout.createSequentialGroup()
                        .addComponent(btnCmdChipName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCmdDigitalInGetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTestLayout.createSequentialGroup()
                        .addComponent(btnCmdDigitalOutGetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCmdMemIntGetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTestLayout.setVerticalGroup(
            pnlTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestLayout.createSequentialGroup()
                .addComponent(lblReply)
                .addGap(2, 2, 2)
                .addComponent(scrollReply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCmd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCmdChipName)
                    .addComponent(btnCmdDigitalInGetAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCmdDigitalOutGetAll)
                    .addComponent(btnCmdMemIntGetAll))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        tabTest.addTab("Test", pnlTest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTest, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabTest, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCmdChipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmdChipNameActionPerformed
        taReply.setText(TGS_Time.toString_timeOnly_now_simplified() + ".chipname: " + TS_SerialComKinConyKC868_A32_R1_2.chipName());
    }//GEN-LAST:event_btnCmdChipNameActionPerformed

    private void btnCmdDigitalInGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmdDigitalInGetAllActionPerformed
        taReply.setText(TGS_Time.toString_timeOnly_now() + ".digitalIn_getAll: " + TS_SerialComKinConyKC868_A32_R1_2.digitalIn_getAll());
    }//GEN-LAST:event_btnCmdDigitalInGetAllActionPerformed

    private void btnCmdDigitalOutGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmdDigitalOutGetAllActionPerformed
       taReply.setText(TGS_Time.toString_timeOnly_now() + ".digitalOut_getAll: " + TS_SerialComKinConyKC868_A32_R1_2.digitalOut_getAll());
    }//GEN-LAST:event_btnCmdDigitalOutGetAllActionPerformed

    private void btnCmdMemIntGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmdMemIntGetAllActionPerformed
        taReply.setText(TGS_Time.toString_timeOnly_now() + ".memInt_getAll: " + TS_SerialComKinConyKC868_A32_R1_2.memInt_getAll());
    }//GEN-LAST:event_btnCmdMemIntGetAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCmdChipName;
    private javax.swing.JButton btnCmdDigitalInGetAll;
    private javax.swing.JButton btnCmdDigitalOutGetAll;
    private javax.swing.JButton btnCmdMemIntGetAll;
    private javax.swing.JLabel lblCmd;
    private javax.swing.JLabel lblReply;
    private javax.swing.JTabbedPane pnlMonitor;
    private javax.swing.JPanel pnlTest;
    private javax.swing.JScrollPane scrollReply;
    private javax.swing.JTextArea taReply;
    private javax.swing.JTabbedPane tabTest;
    // End of variables declaration//GEN-END:variables
}
